// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_server

type Billing interface {
	IsBilling()
}

type MFKAccountTransferNotification struct {
	ID                            string `json:"id"`
	SenderName                    string `json:"senderName"`
	AccountTransferNotificationID string `json:"accountTransferNotificationID"`
}

func (MFKAccountTransferNotification) IsBilling() {}

type MFKInvoice struct {
	ID         string `json:"id"`
	SenderName string `json:"senderName"`
	InvoiceID  string `json:"invoiceID"`
}

func (MFKInvoice) IsBilling() {}
